name: Dev Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  trigger-test:
    runs-on: windows-latest
    steps:
      - name: Trigger automated tests in apiAutomation repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.API_ACCESS_TOKEN }}  # ✅ Securely using the secret
          repository: MuhammadZeeshan07/apiAutomation
          event-type: run-tests
          client-payload: '{"triggered_by": "Dev Repo"}'
