name: Dev Test and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-playwright-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Playwright Test Repo
      uses: actions/checkout@v4
      with:
        repository: MuhammadZeeshan07/YoucaterTestSuite
        token: ${{ secrets.WEB_ACCESS_TOKEN }}
        path: YoucaterTestSuite

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: ./YoucaterTestSuite

    - name: Install Playwright browsers
      run: npx playwright install
      working-directory: ./YoucaterTestSuite

    - name: Run Playwright Tests
      run: npx playwright test tests/suite.test.js
      working-directory: ./YoucaterTestSuite

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: YoucaterTestSuite/playwright-report/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: YoucaterTestSuite/test-results/

  deploy:
    runs-on: windows-latest
    needs: run-playwright-tests
    if: success()

    steps:
    - name: Checkout Dev Repo
      uses: actions/checkout@v4

    - name: Deploy Step
      run: echo "Deployment started..."
