name: Dev Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  trigger-test-repo:
    runs-on: windows-latest
    steps:
      - name: Send repository dispatch event
        shell: pwsh  # Explicitly use PowerShell
        run: |
          Invoke-RestMethod -Uri "https://github.com/MuhammadZeeshan07/apiAutomation/dispatches" `
            -Method Post `
            -Headers @{
                Authorization = "token ${{ secrets.ACCESS_TOKEN }}"
                Accept = "application/vnd.github.v3+json"
            } `
            -Body '{"event_type": "run-tests"}' `
            -ContentType "application/json"
