name: Run API Tests

on:
  workflow_dispatch:  # Allows manual trigger
  repository_dispatch:  # Allows trigger from another repository
    types: [run-tests]  # Custom event name

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn test -PSanity
