name: Dev Test and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Test Repo (apiAutomation)
      uses: actions/checkout@v4
      with:
        repository: MuhammadZeeshan07/apiAutomation
        token: ${{ secrets.API_ACCESS_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run API Tests
      run: mvn test -PSanity

  deploy:
    runs-on: windows-latest
    needs: run-tests
    if: success()

    steps:
    - name: Checkout Dev Repo
      uses: actions/checkout@v4

    - name: Deploy Step
      run: echo "Deployment started..."
