name: Dev Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    uses: MuhammadZeeshan07/apiAutomation/.github/workflows/reusable-test.yml@master
    with: {}
    secrets:
      API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}

  deploy:
    runs-on: windows-latest
    needs: run-tests
    if: success()

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "✅ Deploying because tests passed!"
