name: Dev Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  trigger-test:
    runs-on: windows-latest  # Using Linux instead of Windows for API calls
    steps:
      - name: Trigger automated tests in apiAutomation repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}  # PAT (Personal Access Token) required
          repository: MuhammadZeeshan07/apiAutomation
          event-type: run-tests  # Must match the event in apiAutomation repo
          client-payload: '{"triggered_by": "Dev Repo"}'
